# Generated by Django 3.0.8 on 2021-05-29 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_auto_20210529_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('packages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.packages')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
