# Generated by Django 3.0.8 on 2021-10-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_packages_itinerary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagesbook',
            name='guest',
            field=models.IntegerField(),
        ),
    ]
