# Generated by Django 3.0.8 on 2021-09-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cairotour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cairotour',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
