# Generated by Django 3.0.8 on 2021-05-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxortour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='luxortour',
            name='name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
