# Generated by Django 3.0.8 on 2021-09-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxortour', '0002_luxortour_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='luxortour',
            name='itinerary',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
