# Generated by Django 3.0.8 on 2021-06-02 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Post', '0013_auto_20210429_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='slideImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namee', models.CharField(max_length=50)),
                ('image3', models.ImageField(blank=True, null=True, upload_to='main_product')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='main_product')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
