# Generated by Django 3.0.8 on 2021-07-21 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0016_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main_product'),
        ),
    ]
