# Generated by Django 3.0.8 on 2021-09-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0017_auto_20210722_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slideimages',
            name='Luxor',
        ),
        migrations.RemoveField(
            model_name='slideimages',
            name='aswan',
        ),
        migrations.RemoveField(
            model_name='slideimages',
            name='makeatrip',
        ),
        migrations.RemoveField(
            model_name='slideimages',
            name='tourpackages',
        ),
        migrations.AddField(
            model_name='slideimages',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='main_product'),
        ),
        migrations.AddField(
            model_name='slideimages',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='main_product'),
        ),
    ]
