# Generated by Django 3.0.8 on 2021-09-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0018_auto_20210930_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(max_length=100, verbose_name='Comment :'),
        ),
    ]
