# Generated by Django 3.0.8 on 2021-05-30 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='aswan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luxor', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='cairo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cairo', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='giza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giza', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='hurghada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giza', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='luxor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luxor', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='makeatrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Departure', models.DateTimeField(default=django.utils.timezone.now)),
                ('arrival', models.DateTimeField(default=django.utils.timezone.now)),
                ('guest', models.CharField(choices=[(' 1 ', '1 '), ('2 ', '2'), ('3', '3'), ('4', '4')], max_length=100)),
                ('phone_number', models.CharField(max_length=12)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('aswan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aswan_category', to='makeatrip.aswan')),
                ('cairo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cairo_category', to='makeatrip.cairo')),
                ('giza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giza_category', to='makeatrip.giza')),
                ('hurghada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hurghada_category', to='makeatrip.hurghada')),
                ('luxor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luxor_category', to='makeatrip.luxor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
