# Generated by Django 3.0.8 on 2021-05-30 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeatrip', '0002_auto_20210530_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aswan',
            old_name='luxor',
            new_name='aswan',
        ),
        migrations.RenameField(
            model_name='hurghada',
            old_name='giza',
            new_name='hurghada',
        ),
    ]
