# Generated by Django 3.0.8 on 2021-05-31 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makeatrip', '0004_auto_20210531_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeatrip',
            name='aswan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aswan_category', to='makeatrip.aswan'),
        ),
    ]
