# Generated by Django 3.0.8 on 2021-05-31 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makeatrip', '0005_auto_20210531_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeatrip',
            name='cairo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cairo_category', to='makeatrip.cairo'),
        ),
        migrations.AlterField(
            model_name='makeatrip',
            name='giza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='giza_category', to='makeatrip.giza'),
        ),
        migrations.AlterField(
            model_name='makeatrip',
            name='hurghada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hurghada_category', to='makeatrip.hurghada'),
        ),
        migrations.AlterField(
            model_name='makeatrip',
            name='luxor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='luxor_category', to='makeatrip.luxor'),
        ),
    ]
