# Generated by Django 3.0.8 on 2021-09-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilecruise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nilecruise',
            name='itinerary',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
