# Generated by Django 3.0.8 on 2021-03-27 18:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neme', models.CharField(max_length=100, verbose_name='الاسم الكامل :')),
                ('Section', models.CharField(max_length=100, verbose_name='القسم :')),
                ('phone', models.CharField(max_length=12, verbose_name='تليفون  :')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الالكترونى الجامعى :')),
                ('image', models.FileField(upload_to='profile/', verbose_name='الصورة الشخصية  :')),
                ('image2', models.FileField(upload_to='profile/', verbose_name='صورة البطاقة الشخصية  :')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
