# Generated by Django 3.0.8 on 2021-03-30 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='property_category', to='property.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='properimages',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proper_Images', to='property.property'),
        ),
    ]
