# Generated by Django 3.0.8 on 2021-03-30 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20210330_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyreview',
            old_name='price',
            new_name='pricee',
        ),
        migrations.RenameField(
            model_name='propertyreview',
            old_name='property',
            new_name='propertyy',
        ),
    ]
