# Generated by Django 3.0.8 on 2021-03-31 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20210330_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertybook',
            old_name='date_from',
            new_name='datesfrom',
        ),
    ]
