# Generated by Django 3.0.8 on 2021-04-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_property_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(default=1, upload_to='property/'),
            preserve_default=False,
        ),
    ]
