# Generated by Django 3.0.8 on 2021-04-05 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20210405_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertybook',
            name='active',
        ),
        migrations.RemoveField(
            model_name='propertybook',
            name='created',
        ),
    ]
