# Generated by Django 3.0.8 on 2021-10-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20210417_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertybook',
            name='guest',
            field=models.IntegerField(default=0),
        ),
    ]
